### ISSUE TITLE
Update dependencies and clean package.json

### ISSUE THREAD

**Issue by noelmace** [Sfeir/angular-200#92]
Follow update.angular.io in order to update to following dependencies to their latest versions:
- @angular/cli
- @angular/core
- @angular/cdk
- @angular/material
- @ngrx/store
- rxjs

Verify potential conflicts with step branches, put all the required dependencies in master, and then clean unused dependencies.

**Comment by geromegrignon** [comment]
i'll work on it.

**Comment by noelmace** [comment]
I keep this issue open in order to do a last update before the next session at the end of this month.
