### ISSUE TITLE
write a proper README

### ISSUE THREAD

**Issue by noelmace** [Sfeir/angular-200#96]
For now, README.md is just the one generated by default by angular-cli. We should had informations about the course itself (slides link, timing, how to use the steps, etc...).

**Comment by geromegrignon** [comment]
Do you want a french or english version?

**Comment by noelmace** [comment]
I think a french one would be better given that we only give this in french, but not sure. I should check with @cbalit.

**Comment by noelmace** [comment]
Yeah, maybe we should use french here too :smile: I'm just used to write everything in english on Github ...
Great idea thx!

**Comment by noelmace** [comment]
Ok for a french version, but as their is some chance that this school may be given in english in a near futur, we'll keep issues and commits in english, and we'll also need an english versiion of this README later.

**Comment by geromegrignon** [comment]
Pull request done.

**Comment by geromegrignon** [comment]
Once the #93 will be completed, i'll consider adding a "Learning materials" section with links to additional content like : 
- ngrx.io
- angular console
...
